language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t nimanthaprasan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nimanthaprasan/react-test npm run test

after_success: 
  - docker build -t nimanthaprasan/multi-client ./client
  - docker build -t nimanthaprasan/multi-nginx ./nginx
  - docker build -t nimanthaprasan/multi-server ./server
  - docker build -t nimanthaprasan/multi-worker ./worker
  # login into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take all the built images and push to the DockerHub
  - docker push nimanthaprasan/multi-client
  - docker push nimanthaprasan/multi-nginx
  - docker push nimanthaprasan/multi-server
  - docker push nimanthaprasan/multi-worker
  
#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "docker-react"
#  env: "Dockerreact-env"
#  bucket_name: "elasticbeanstalk-us-east-2-049149386064"
#  bucket_path: "docker-react"
#  on: 
#    branch: master
#  access_key_id: "$AWS_ACCESS_KEY"
#  secret_access_key: "$AWS_SECRET_KEY"
#  skip_cleanup: true